spring:
  application:
    name: order-worker

camunda.bpm.client:
  base-url: http://camunda-service:8080/engine-rest
  lock-duration: 10000

server:
  port: 8086

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true
    hostname: ${HOSTNAME}